DROP TABLE PocketList;
DROP TABLE  PRODUCT;
DROP TABLE  MEMBER;

CREATE TABLE MEMBER (
	ID	VARCHAR2(30)	NOT NULL ,
	PASSWD	VARCHAR2(30)	NOT NULL	 ,
	NAME	VARCHAR2(20)	NOT NULL	 ,
	TEL	NUMBER	NOT NULL	 ,
	BRITHDAY NUMBER	NOT NULL	,
	GENDER	CHAR(1)	NOT NULL
);



CREATE TABLE PRODUCT (
	Pocket	NUMBER	NULL,
	goodsname	VARCHAR(100)	NULL,
	price	NUMBER	NULL,
    productimg	VARCHAR(200)	NULL
);



CREATE TABLE PocketList (
	ID	VARCHAR2(30)	NOT NULL,
	Pocket	NUMBER	NULL,
    times	DATE	NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT PK_MEMBER PRIMARY KEY (
	ID
);

ALTER TABLE PRODUCT ADD CONSTRAINT PK_PRODUCT PRIMARY KEY (
	Pocket
);

ALTER TABLE PocketList ADD CONSTRAINT PK_POCKETLIST PRIMARY KEY (
	ID,
	Pocket
);

ALTER TABLE PocketList ADD CONSTRAINT FK_MEMBER_TO_PocketList_1 FOREIGN KEY (
	ID
)
REFERENCES MEMBER (
	ID
);

ALTER TABLE PocketList ADD CONSTRAINT FK_PRODUCT_TO_PocketList_1 FOREIGN KEY (
	Pocket
)
REFERENCES PRODUCT (
	Pocket
);

insert into member values('user1', 'user1', '성철', 1234, 980415, 'M');
insert into member values('user2', 'user2', '하하', 1234, 980416, 'W');
commit;
desc member;